# Generated by Django 5.1.3 on 2025-01-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('evaluation_result', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
