# Generated by Django 5.1.3 on 2025-01-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_trainer', '0002_transcription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('job_description', models.TextField()),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('social_links', models.TextField(blank=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('fresher_or_professional', models.CharField(max_length=20)),
            ],
        ),
    ]
